# Generated by Django 3.2.7 on 2021-09-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_site', '0006_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
