# Generated by Django 3.2.7 on 2021-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_site', '0010_alter_review_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book_id',
            field=models.BigIntegerField(auto_created=True),
        ),
    ]
