# Generated by Django 3.2.7 on 2021-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_site', '0014_auto_20210930_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='buyer_site.Author'),
        ),
    ]
