# Generated by Django 3.2.7 on 2021-10-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_site', '0015_alter_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='mary', max_length=256),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
